config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :subs do
    # provides a route to get all the articles for a given magazine.
    resources :posts, only: [:create, :index]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, except: [:new]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :string
#  user_id           :integer
#  post_id           :integer
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ActiveRecord::Base

  validates :content, :user, :post, presence: true

  belongs_to :user
  belongs_to :post

  belongs_to(
    :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    primary_key: :id
    )

  has_many(
  :child_comments,
  foreign_key: :parent_comment_id,
  class_name: :Comment,
  primary_key: :id
  )

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  url        :string
#  content    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  # attr_reader :in_subs
  validates :title, :user, presence: true

  belongs_to :user
  has_many :post_subs, dependent: :destroy

  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )

  has_many :comments

  def comments_by_parent_id
    hash = Hash.new { |h, k| h[k] = [] }
    self.comments.includes(:user).each do |comment|
      hash[comment.parent_comment_id] += [comment]
    end
    hash
  end
  # def sub_ids=(sub_ids)
  #   in_subs=[]
  #   sub_ids.each do |sub_id|
  #     in_subs += [PostSub.new(sub_id: sub_id, post_id: self.id)]
  #   end
  #   @in_subs=in_subs
  # end

end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  belongs_to :sub
  belongs_to :post
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, presence: true
  has_many :post_subs, dependent: :destroy

  has_many(
    :posts,
    through: :post_subs,
    source: :post
  )

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :user_id
  )
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  has_many :posts
  has_many :subs
  has_many :comments

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    # should save right?
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user(user)
    @current_user = user
    session[:session_token] = user.session_token
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new

  end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_url(params[:post_id])
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to post_url(params[:post_id])
    end
  end

  def comment_params
    params[:comment].permit(:content, :user_id, :post_id, :parent_comment_id)
  end

  def show
    @comment = Comment.find(params[:id])
    @comments_by_parent_id=Post.find(@comment.post_id).comments_by_parent_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :validate_post_author, only: [:edit, :update]

  def create
    # subpost = Sub.find(params[:sub_id])
    @post = current_user.posts.new(post_params)
    # @post.user_id = current_user.id
    if @post.save
      redirect_to sub_url(params[:sub_id])
      # @post.in_subs.each do |in_sub|
      #   in_sub.post_id = @post.id
      #   in_sub.save
      # end
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to sub_url(params[:sub_id])
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
    @all_comments = @post.comments.includes(:user)
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private

  def validate_post_author
    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless @post.user_id = current_user.id
  end

  def post_params
    params[:post].permit(:title, :url, :content, :user_id, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["wrong credentials"]
      render :new
    else
      login_user(user)
      redirect_to users_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :validate_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
  end

  def create
    @sub = current_user.subs.new(sub_params)
    # @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params[:sub].permit(:title, :description, :user_id)
  end

  def validate_moderator
    subpost = Sub.find(params[:id])
    redirect_to sub_url(subpost) unless subpost.user_id == current_user.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show

  end

  def user_params
    params[:user].permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= User.find(comment.user_id).username %>
<%= link_to comment.content, comment_url(comment) %>
<% comment.child_comments.each do |child_comment| %>
<ul>
  <%= render 'comment', comment: child_comment %>
</ul>
<% end %>
<br>

app/views/comments/show.html.erb
<%= render 'posts/comment', comment: @comment,
 comments_by_parent_id: @comments_by_parent_id%>

<form action="/posts/<%= @comment.post_id %>/comments" method="post">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>"
  <label for="content">Content</label>
  <input type="text" name="comment[content]" id="title">
  <input type="submit" value="create comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<% if flash[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>


<% if current_user.nil? %>
  <%= link_to "log_in", new_session_url %>
  <%= link_to "sign_up", new_user_url %>
<% else %>
  <%= current_user.username %>
  <%= link_to "subs", subs_url %>
  <%= button_to "log_out", session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
<%= comment.user.username %>
<%= link_to comment.content, comment_url(comment) %>
<% comments_by_parent_id[comment.id].each do |child_comment| %>
  <ul>
    <% if child_comment.parent_comment_id == comment.id %>
      <%= render 'comment', comment: child_comment, comments_by_parent_id: comments_by_parent_id %>
    <% end %>
  </ul>
<% end %>
<br>

app/views/posts/edit.html.erb
<p>Edit subpost</p>
<form action="/subs/<%= @sub.id %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <label for="title">Title</label>
  <input type="text" name="sub[title]" id="title">
  <label for="description">Description</label>
  <input type="text" name="sub[description]" id="description">
  <input type="submit" value="edit subpost">
</form>

app/views/posts/new.html.erb
<p>Create Subpost</p>
<form action="/subs" method="post">
  <label for="title">Title</label>
  <input type="text" name="sub[title]" id="title">
  <label for="description">Description</label>
  <input type="text" name="sub[description]" id="description">
  <input type="submit" value="create subpost">
</form>

app/views/posts/show.html.erb
Post title: <%= @post.title %>
Post content: <%= @post.content %>

<br>

<% @post.comments_by_parent_id[nil].each do |comment| %>
  <%= render 'comment', comment: comment,
   comments_by_parent_id: @post.comments_by_parent_id%>
<% end %>

<p>Create new comment</p>
post_comments

<form action="/posts/<%= @post.id %>/comments" method="post">
  <label for="content">Content</label>
  <input type="text" name="comment[content]" id="title">
  <input type="submit" value="create comment">
</form>

app/views/subs/edit.html.erb
<p>Edit subpost</p>
<form action="/subs/<%= @sub.id %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <label for="title">Title</label>
  <input type="text" name="sub[title]" id="title">
  <label for="description">Description</label>
  <input type="text" name="sub[description]" id="description">
  <input type="submit" value="edit subpost">
</form>

app/views/subs/index.html.erb
this is the index for subs

<% @subs.each do |subpost| %>
<%= link_to subpost.title, sub_url(subpost.id) %>
<%= subpost.description %>
<br>
<% end %>

<%= link_to "create new sub", new_sub_url %>

app/views/subs/show.html.erb
<%= @sub.title %>


<%= @sub.description %>

</ul>
<% @sub.posts.each do |post| %>
<li>
  <%= link_to post.title, post_url(post) %>
  <%= User.find(post.user_id).username %>
  <%= post.content %>
  <% if current_user == User.find(post.user_id)%>
    <form action="/posts/<%= post.id %>" method="post">
      <input type="hidden" name="_method" value="patch">
      <label for="title">Title</label>
      <input type="text" name="post[title]" id="title">
      <label for="content">Content</label>
      <input type="text" name="post[content]" id="content">
      <input type="submit" value="edit post">
      <% Sub.all.each do |subpost| %>
        <label>
          <input type="checkbox" name="post[sub_ids][]" value="<%= subpost.id %>"
            <%= "checked" if post.subs.include?(subpost) %> >
          <%= subpost.title %>
        </label>
        <br>
      <% end %>
    </form>
  <% end %>
</li>
<% end %>

</ul>

<p>Create new post</p>
<form action="/subs/<%= @sub.id %>/posts" method="post">
  <label for="title">Title</label>
  <input type="text" name="post[title]" id="title">
  <label for="content">Content</label>
  <input type="text" name="post[content]" id="content">
  <input type="submit" value="create post">
  <% Sub.all.each do |subpost| %>
    <label>
      <% if @sub == subpost %>
        <input type="checkbox" name="post[sub_ids][]" value="<%= subpost.id %>" checked>
        <%= subpost.title %>
      <% else %>
        <input type="checkbox" name="post[sub_ids][]" value="<%= subpost.id %>">
        <%= subpost.title %>
      <% end %>
    </label>
    <br>
  <% end %>

</form>

app/views/users/index.html.erb
this is the index

app/views/users/new.html.erb
<form action="/users" method="post">
  <label for="username">Username</label>
  <input type="text" name="user[username]" id="username">
  <label for="password">Password</label>
  <input type="text" name="user[password]" id="password">
  <input type="submit" value="sign_up">
</form>